Add about activity
furzeal/android-academy-ny-times pull request #1
Opened 2018-10-07 13:23 UTC by furzeal

Можно рассматривать в качестве ДЗ №2

2018-10-08 08:44 UTC, user32338 commented
А где русский язык?

2018-10-08 09:06 UTC, user32338 requested changes

2018-10-08 09:06 UTC, user32338 commented on app/src/main/res/layout/activity_about.xml
> +            android:layout_width="wrap_content"
а у нас вроде картинка по ширине экрана должна быть, а у тебя не так

2018-10-08 09:06 UTC, user32338 commented on app/src/main/res/layout/activity_about.xml
> +            android:layout_width="match_parent"
у тебя кнопка во всю ширину, и можно нажать вне текста это не правильно, нужно пржать ее к правой стороне panret и сделать wrap_content + отсутпы если нужно

2018-10-09 16:41 UTC, furzeal commented
Поправил замечания

2018-10-09 16:43 UTC, user32338 approved these changes

2018-10-09 18:51 UTC, merged